### ISSUE TITLE
Create rewards module for Incentive rewards

### ISSUE THREAD

**Issue by arnabmitra** [provenance-io/provenance#726] opened 2022-03-14 21:49 UTC
## Summary

Create rewards module for Incentive rewards

## Problem Definition

To implement incentive rewards, following functionality is needed from the rewards module
* Create a reward criteria mechanism
* Create a total pool for each reward criteria
* Create a way to record claims for rewards
*  Each claim is a share of the `total pool for each reward criteria`
*  Claims can be negative too ( i.e reduce shares earned per address)
*  Distribute each claim(i.e each share of the pool) per address. This mechanism i believe should be user driven( Similar to claiming validator rewards)
*  Rewards claim may expire.

## Proposal

Create a module to accomplish all the above.
Flow for reward criteria creation/distribution is as follows
* Rewards criteria are created by governance
* Only supported source of fund will be community pool for now.( i.e gov proposal creation should ensure sufficient funds are present), move them to escrow and if gov proposal fails return them.
 funds pledged will be moved to an escrow account(`rewards_module`+ `rewards_id` bech 32 is the escrow address)
* Once Governance proposal passes, rewards criteria will be marked as active.
* Each epoch is equally divided in terms of rewards i.e `total rewards/ total epochs program runs for`, hence small epochs are discouraged but up to the group providing the rewards.
For e.g staking action per epoch, should ideally be a `monthly` epoch, rather than daily
* Each action get's +ve share recorded, at the end of the epoch rewards per epoch is divided between each share
 for e.g lets say an epoch is daily and per epoch we have 100nhash to give out, based on the number of shares ( i.e actions taken), lets say that is 100, so each action will get 1hash.
We can/should put a limit on the max amount address can get, or think of ways where a maximum threshold amount triggers the action for e.g staking 1000hash only triggers an action etc.
There should also be a whitelist to ignore rewards given out to.
* On epoch end only total shares accrued for that epoch is recorded, total rewards per epoch  should be recorded (accounting for non uniform distribution).
* A user can see how many participation rewards can be claimed by him for a reward id.
* A user crafts a message to claim these rewards available to him at any time
* A rewards criteria may have an expiration, at which time all unclaimed rewards are returned to community pool.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by channa-figure** [comment] 2022-04-19 19:56
Duplicate of #627

**Closed by channa-figure** 2022-04-19 19:56 UTC
Labels: incentive
