### ISSUE TITLE
Wasm cli flag registration bug

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#1428] opened 2023-03-16 19:56 UTC
## Summary of Bug

The `wasmd` module appears to have flags incorrectly registered.

```
provenanced --node=https://rpc.provenance.io:443 q wasm list-contracts-by-creator pb104se9kqx2tzfc8u8r9xnhcdfjgy340eh7jlpuv
panic: flag accessed but not defined: page-key

goroutine 1 [running]:
github.com/CosmWasm/wasmd/x/wasm/client/cli.withPageKeyDecoded(0x16fba7a62?)
	github.com/CosmWasm/wasmd@v0.29.0/x/wasm/client/cli/query.go:618 +0xec
github.com/CosmWasm/wasmd/x/wasm/client/cli.GetCmdListContractsByCreator.func1(0x14001740c00?, {0x14001174600, 0x1, 0x2?})
	github.com/CosmWasm/wasmd@v0.29.0/x/wasm/client/cli/query.go:548 +0xb0
github.com/spf13/cobra.(*Command).execute(0x14001740c00, {0x140011745e0, 0x2, 0x2})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c4
github.com/spf13/cobra.(*Command).ExecuteC(0x14001658300)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x340
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.6.1/command.go:961
github.com/provenance-io/provenance/cmd/provenanced/cmd.Execute(0x14000084768?)
	github.com/provenance-io/provenance/cmd/provenanced/cmd/root.go:142 +0x280
main.main()
	github.com/provenance-io/provenance/cmd/provenanced/main.go:14 +0x20
provenanced --node=https://rpc.provenance.io:443 q wasm list-contracts-by-creator pb104se9kqx2tzfc8u8r9xnhcdfjgy340eh7jlpuv                                          Thu Mar 16 13:47:32 2023
panic: flag accessed but not defined: page-key

goroutine 1 [running]:
github.com/CosmWasm/wasmd/x/wasm/client/cli.withPageKeyDecoded(0x16fba7a62?)
	github.com/CosmWasm/wasmd@v0.29.0/x/wasm/client/cli/query.go:618 +0xec
github.com/CosmWasm/wasmd/x/wasm/client/cli.GetCmdListContractsByCreator.func1(0x14001740c00?, {0x14001174600, 0x1, 0x2?})
	github.com/CosmWasm/wasmd@v0.29.0/x/wasm/client/cli/query.go:548 +0xb0
github.com/spf13/cobra.(*Command).execute(0x14001740c00, {0x140011745e0, 0x2, 0x2})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c4
github.com/spf13/cobra.(*Command).ExecuteC(0x14001658300)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x340
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.6.1/command.go:961
github.com/provenance-io/provenance/cmd/provenanced/cmd.Execute(0x14000084768?)
	github.com/provenance-io/provenance/cmd/provenanced/cmd/root.go:142 +0x280
main.main()
	github.com/provenance-io/provenance/cmd/provenanced/main.go:14 +0x20
```

## Version

v1.14.0+

## Steps to Reproduce

```
provenanced --node=https://rpc.provenance.io:443 q wasm list-contracts-by-creator pb104se9kqx2tzfc8u8r9xnhcdfjgy340eh7jlpuv
```

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment] 2023-05-03 20:57
This is caused by using `ReadPageRequest` in a command without applying `AddPaginationFlagsToCmd` to it.

In our fork of `wasmd`, as of `v0.30.0-pio-4`, the only file where `ReadPageRequest` is used is in `x/wasm/client/cli/query.go`. The only cmd that uses `ReadPageRequest` without `AddPaginationFlagsToCmd` is `GetCmdListContractsByCreator`.

So the fix for this will be to add this line:
```
flags.AddPaginationFlagsToCmd(cmd, "contracts by creator")
```
before the `return cmd` line at the end of `flags.AddPaginationFlagsToCmd(cmd, "contracts by creator")`

I'm stating it here instead of just doing it because, in order to get it into `provenanced`, we'd need to tag a new version and bump it in the `provenance` repo. I'd rather not do that until after `v1.15.0` is out and in use.

**Comment by SpicyLemon** [comment] 2023-05-19 23:38
A `wasmd` PR has been merged into `notional-labs-46.7-pio-release` which will fix this. I'm holding off on tagging a new `wasmd` release, though, until some other stuff can get in there.

As long as `v0.30.0-pio-5` (or whatever our next `wasmd` version is) is based off that branch, this issue will be resolved once we bump `wasmd` in the provenance repo.

I'm going to leave this issue open and unassigned until then though.

You can easily check it by running `build/provenanced q wasm list-contracts-by-creator pb104se9kqx2tzfc8u8r9xnhcdfjgy340eh7jlpuv`. If you get a bech32 prefix error, try `tp104se9kqx2tzfc8u8r9xnhcdfjgy340ehde6d7x` instead. If it panics due to the page key, it's not fixed. Otherwise, it's fixed and this issue can be closed.

**Comment by SpicyLemon** [comment] 2023-06-09 22:42
The fix for this will get pulled in with #1584.

**Closed** 2023-06-12 21:49 UTC
Labels: bug, wasm
