### ISSUE TITLE
Binary also no good, any ideas?

### ISSUE THREAD

**Issue by TurtleSnail** [provenance-io/provenance#1867] opened 2024-03-06 11:04 UTC
```
$ ./bin/provenanced 
./bin/provenanced: error while loading shared libraries: libleveldb.so.1: cannot open shared object file: No such file or directory
```

obvisouly I need that library, but how to get?

**Comment by Taztingo** [comment] 2024-03-06 14:37
How did you obtain this binary? Did you build this binary, or did you obtain it from our releases? Is this for arm or amd/x86?

You should be able to obtain that library by running `make cleveldb` in our repository.

**Comment by mcf-rocks** [comment] 2024-03-07 05:12
I obtained it from your release (the assets on github under the release)

**Comment by TurtleSnail** [comment] 2024-03-09 11:55
the binary was downloaded from the assets on github.

**Comment by Taztingo** [comment] 2024-03-10 05:13
Closing because this is a duplicate of #1782, and is working as intended for this release. We have deprecated cleveldb please consider switching to goleveldb.

**Closed by Taztingo** 2024-03-10 05:13 UTC

**Comment by smithit2000** [comment] 2024-03-10 05:47
So you released binaries that don't work?
