### ISSUE TITLE
Authz support for message type URLs with anchors

### ISSUE THREAD

**Issue by egaxhaj** [provenance-io/provenance#568] opened 2021-12-14 16:03 UTC
## Summary

Investigate if `authz` grants can be added for type URLs with anchors.

For example: Granting access to `/provenance.metadata.v1.MsgWriteScopeRequest#scope1qzge0zaztu65tx5x5llv5xc9ztsqxlkwel`

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment] 2023-09-06 19:34
Duplicate of #1439

**Closed by SpicyLemon** 2023-09-06 19:34 UTC
